name: Using Action almerindo/action-env-from-aws-ssm

on:
  push:
    branches: [ main]

jobs:
  ghAction:
    runs-on: ubuntu-latest
    steps:
      - uses: almerindo/action-env-from-aws-ssm
        with:
          ssm-path: /whitebeard/action-env-from-aws-ssm
          format: yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - run: cat .env